version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
            python manage.py autosuperuser --username admin --email ${DJANGO_SUPERUSER_EMAIL} --password ${DJANGO_SUPERUSER_PASSWORD} &&
             python manage.py collectstatic --noinput &&
             gunicorn ispms.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8090"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      DATABASE_URL: ${DATABASE_URL} # NEON PostgreSQL
      BKASH_APP_KEY: ${BKASH_APP_KEY}
      BKASH_APP_SECRET: ${BKASH_APP_SECRET}
      BKASH_USERNAME: ${BKASH_USERNAME}
      BKASH_PASSWORD: ${BKASH_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  celery:
    build: .
    command: celery -A ispms worker --loglevel --info
      
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A ispms beat --loglevel --info
    depends_on:
      - redis

volumes:
  redis-data:
