# Generated by Django 5.1.1 on 2024-09-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_area_admin_package_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='admin',
            new_name='area_admin',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='admin',
            new_name='pkg_admin',
        ),
    ]
