# Generated by Django 5.1.1 on 2024-09-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_admin_area_area_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
