# Generated by Django 5.1.1 on 2024-09-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
