# Generated by Django 5.1.1 on 2024-09-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
