# Generated by Django 5.1.1 on 2024-10-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=12345, max_length=110),
            preserve_default=False,
        ),
    ]
