# Generated by Django 5.1.1 on 2024-10-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
