# Generated by Django 5.1.1 on 2024-09-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscriptionplan_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'permissions': [('can_access_advanced_feature', 'Can access advanced feature'), ('can_use_premium_feature', 'Can use premium feature'), ('can_use_basic_feature', 'Can use basic feature')]},
        ),
    ]
