# Generated by Django 5.1.1 on 2024-09-15 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscription', '0006_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='auth.group'),
        ),
    ]
