# Generated by Django 5.1.1 on 2024-09-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_subscriptionplan_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='customer_limit',
            field=models.PositiveIntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='installation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
