# Generated by Django 5.1.1 on 2024-09-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_subscriptionplan_customer_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='customer_limit',
            field=models.PositiveIntegerField(),
        ),
    ]
