# Generated by Django 5.1.1 on 2024-10-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='installation_fee',
        ),
    ]
