# Generated by Django 5.1.1 on 2024-10-24 19:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customer_active'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bkash', 'Bkash')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_exec_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 25, 1, 16, 0, 609103), null=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='trxID',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
