# Generated by Django 5.1.1 on 2024-12-04 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_customerpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_exec_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 4, 23, 21, 57, 765434), null=True),
        ),
    ]
