# Generated by Django 5.1.1 on 2024-12-05 05:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_customerpayment_payment_exec_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_exec_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 5, 11, 44, 53, 685337), null=True),
        ),
    ]
