# Generated by Django 5.1.1 on 2024-12-08 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_customerpayment_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_exec_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 8, 21, 5, 4, 77984), null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='trxID',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
