# Generated by Django 5.1.1 on 2024-12-08 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_customerpayment_payment_exec_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_exec_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 9, 0, 17, 40, 184375), null=True),
        ),
    ]
