# Generated by Django 5.1.1 on 2024-09-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
