# Generated by Django 5.1.1 on 2024-09-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customuser_customer_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mikrotik_host',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mikrotik_host_verify_ssl',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mikrotik_password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mikrotik_port',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mikrotik_use_ssl',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mikrotik_username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mikrotik_verify_ssl',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
