# Generated by Django 5.1.1 on 2024-09-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_mikrotik_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mikrotik_host_verify_ssl',
            new_name='mikrotik_ssl_verify_hostname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bkash_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
