# Generated by Django 5.1.1 on 2024-12-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_mikrotik_host_verify_ssl_customuser_mikrotik_ssl_verify_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bkash_app_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bkash_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bkash_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bkash_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
