# Generated by Django 5.1.1 on 2024-09-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='duration',
            field=models.CharField(choices=[('1 Month', '1 Month'), ('10th of the next month', '10th of next')], max_length=110),
        ),
    ]
