# Generated by Django 5.1.1 on 2024-09-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscriptionplan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={},
        ),
    ]
